---
apiVersion: v1
kind: Namespace
metadata:
  name: payment
  labels:
    istio-injection: enabled

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: payment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: mercari/go-conference-2021-spring-office-hour/payment:latest
        imagePullPolicy: Never
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 250m
            memory: 250Mi
